-- ============================================================
-- V6: Create fees table
-- Handles retake fees and semester-gap (break) fees
-- ============================================================

CREATE TYPE fee_type   AS ENUM ('RETAKE', 'SEMESTER_GAP', 'REGISTRATION', 'OTHER');
CREATE TYPE fee_status AS ENUM ('UNPAID', 'PAID', 'WAIVED');

CREATE TABLE fees (
    id              BIGSERIAL PRIMARY KEY,
    student_id      BIGINT          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    fee_type        fee_type        NOT NULL,
    amount          NUMERIC(10,2)   NOT NULL CHECK (amount >= 0),
    description     TEXT,

    -- Which semester/enrollment this fee relates to
    semester_id     BIGINT          REFERENCES semesters(id) ON DELETE SET NULL,
    enrollment_id   BIGINT          REFERENCES enrollments(id) ON DELETE SET NULL,

    status          fee_status      NOT NULL DEFAULT 'UNPAID',
    due_date        DATE,
    paid_at         TIMESTAMPTZ,
    created_by      BIGINT          REFERENCES users(id) ON DELETE SET NULL,  -- admin
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_fees_student    ON fees (student_id);
CREATE INDEX idx_fees_type       ON fees (fee_type);
CREATE INDEX idx_fees_status     ON fees (status);
CREATE INDEX idx_fees_semester   ON fees (semester_id);

-- ============================================================
-- Fee configuration table (admin-configurable amounts)
-- ============================================================

CREATE TABLE fee_config (
    id          BIGSERIAL PRIMARY KEY,
    fee_type    fee_type        NOT NULL UNIQUE,
    amount      NUMERIC(10,2)   NOT NULL CHECK (amount >= 0),
    description TEXT,
    updated_by  BIGINT          REFERENCES users(id) ON DELETE SET NULL,
    updated_at  TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Default fee amounts (BDT)
INSERT INTO fee_config (fee_type, amount, description) VALUES
    ('RETAKE',       500.00,  'Fee per retaken course'),
    ('SEMESTER_GAP', 1000.00, 'Penalty fee per semester gap/break'),
    ('REGISTRATION', 200.00,  'Per-semester registration fee'),
    ('OTHER',        0.00,    'Miscellaneous fee');

-- ============================================================
-- Function: Auto-generate retake fee when enrollment is retake
-- ============================================================

CREATE OR REPLACE FUNCTION auto_generate_retake_fee()
RETURNS TRIGGER AS $$
DECLARE
    retake_amount NUMERIC;
BEGIN
    IF NEW.is_retake = TRUE THEN
        SELECT amount INTO retake_amount FROM fee_config WHERE fee_type = 'RETAKE';
        INSERT INTO fees (student_id, fee_type, amount, description, semester_id, enrollment_id)
        VALUES (
            NEW.student_id,
            'RETAKE',
            retake_amount,
            'Retake fee auto-generated for enrollment ' || NEW.id,
            NEW.semester_id,
            NEW.id
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_auto_retake_fee
    AFTER INSERT ON enrollments
    FOR EACH ROW EXECUTE FUNCTION auto_generate_retake_fee();

COMMENT ON TABLE  fees                   IS 'Student fee records. Retake fees are auto-generated by trigger.';
COMMENT ON TABLE  fee_config             IS 'Admin-configurable fee amounts by type.';
COMMENT ON COLUMN fees.enrollment_id     IS 'Link to the specific enrollment this fee was raised for (optional).';
COMMENT ON COLUMN fees.paid_at           IS 'Timestamp of payment. NULL means still unpaid.';
