# ============================================================
# application-dev.properties — local development config
# ============================================================

# ── PostgreSQL (Local Native) ──
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/credit_management_db?stringtype=unspecified
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1413}
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA – show SQL in dev ──
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

# ── Flyway ──
spring.flyway.url=jdbc:postgresql://127.0.0.1:5432/credit_management_db
spring.flyway.user=${DB_USERNAME:postgres}
spring.flyway.password=${DB_PASSWORD:1413}

# ── CORS – allow Angular dev server ──
app.cors.allowed-origins=http://localhost:4200
app.jwt.secret=${JWT_SECRET:super_secret_jwt_key_that_is_at_least_256_bits_long}
# ── Logging ──
logging.level.org.flywaydb=INFO
logging.level.org.hibernate.type.descriptor.sql=TRACE


